"""Reports: text, JSON, and HTML. The HTML report itself conforms to the
spec: no scripts, no third parties, system fonts."""

from __future__ import annotations

import html
import json

from .grading import VERDICTS, is_pass
from .models import PageResult, SiteResult


def _fmt_bytes(n: int) -> str:
    return f"{n / 1024:.0f} KB" if n < 1024 * 1024 else f"{n / (1024 * 1024):.2f} MB"


# ---------------------------------------------------------------- text

def to_text(site: SiteResult) -> str:
    lines = []
    lines.append("Certified Web 1.0 - conformance report")
    lines.append(f"Spec edition: {site.spec_edition}")
    if site.checked_at:
        lines.append(f"Checked: {site.checked_at}")
    lines.append("")
    for page in site.pages:
        lines.extend(_page_text(page))
        lines.append("")
    if site.grade:
        verdict = "PASS" if is_pass(site.grade) else "FAIL"
        lines.append(f"Overall grade: {site.grade} ({verdict})")
        if len(site.pages) > 1:
            lines.append("(a site is graded by its worst page)")
    else:
        lines.append("No pages could be checked.")
    return "\n".join(lines)


def _page_text(page: PageResult) -> list[str]:
    lines = [f"== {page.url}"]
    if not page.ok:
        lines.append(f"   COULD NOT CHECK: {page.error}")
        return lines
    lines.append(
        f"   Grade {page.grade}: {page.majors} major, {page.minors} minor"
        f" | {_fmt_bytes(page.weight_bytes)} first-party, {page.request_count} requests"
    )
    for rr in page.rule_results:
        mark = "pass" if rr.passed else ("MAJOR" if rr.majors else "minor")
        lines.append(f"   [{mark:>5}] {rr.rule_id} {rr.name}")
        for occ in rr.occurrences[:5]:
            lines.append(f"           - {occ}")
        if len(rr.occurrences) > 5:
            lines.append(f"           ... and {len(rr.occurrences) - 5} more")
    return lines


# ---------------------------------------------------------------- json

def to_json(site: SiteResult) -> str:
    return json.dumps(site.to_dict(), indent=2)


# ---------------------------------------------------------------- html

_HTML_HEAD = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Certified Web 1.0 - conformance report</title>
<style>
body {{ font-family: Georgia, 'Times New Roman', serif; max-width: 46rem;
       margin: 2rem auto; padding: 0 1rem; line-height: 1.5; color: #222; }}
h1, h2 {{ font-weight: normal; }}
code, td.mono {{ font-family: Consolas, Menlo, monospace; font-size: 0.9em; }}
table {{ border-collapse: collapse; width: 100%; margin: 1rem 0; }}
th, td {{ text-align: left; padding: 0.25rem 0.5rem; border-bottom: 1px solid #ddd;
          vertical-align: top; }}
.grade {{ font-size: 2.5rem; border: 3px solid #222; display: inline-block;
          width: 4rem; text-align: center; }}
.pass {{ color: #1a6b1a; }} .fail {{ color: #a11; }}
ul.occ {{ margin: 0.2rem 0 0.2rem 1rem; padding: 0; font-size: 0.85em; color: #555; }}
footer {{ margin-top: 3rem; font-size: 0.85em; color: #777; }}
</style>
</head>
<body>
<h1>Certified Web 1.0 - conformance report</h1>
<p>Spec edition {edition}.{checked}</p>
"""


def to_html(site: SiteResult) -> str:
    checked = f" Checked {html.escape(site.checked_at)}." if site.checked_at else ""
    parts = [_HTML_HEAD.format(edition=html.escape(site.spec_edition), checked=checked)]
    if site.grade:
        cls = "pass" if is_pass(site.grade) else "fail"
        parts.append(
            f'<p><span class="grade {cls}">{site.grade}</span></p>'
            f"<p>{html.escape(VERDICTS[site.grade])}"
            + (" A site is graded by its worst page.</p>" if len(site.pages) > 1 else "</p>")
        )
    for page in site.pages:
        parts.append(_page_html(page))
    parts.append(
        "<footer>Generated by web10-checker. This report contains no scripts, "
        "no third-party resources, and no cookies.</footer>\n"
        "</body>\n</html>\n"
    )
    return "".join(parts)


def _page_html(page: PageResult) -> str:
    out = [f"<h2>{html.escape(page.url)}</h2>"]
    if not page.ok:
        out.append(f"<p class='fail'>Could not check: {html.escape(page.error or '')}</p>")
        return "".join(out)
    cls = "pass" if is_pass(page.grade or "F") else "fail"
    out.append(
        f"<p>Grade <strong class='{cls}'>{page.grade}</strong> - "
        f"{page.majors} major, {page.minors} minor; "
        f"{_fmt_bytes(page.weight_bytes)} first-party transfer, "
        f"{page.request_count} requests.</p>"
    )
    out.append("<table><tr><th>Rule</th><th>Fault</th><th>Result</th></tr>")
    for rr in page.rule_results:
        if rr.passed:
            result = "<span class='pass'>pass</span>"
        else:
            label = "MAJOR" if rr.majors else f"{rr.minors} minor"
            occs = "".join(
                f"<li>{html.escape(o)}</li>" for o in rr.occurrences[:5]
            )
            more = (
                f"<li>&hellip; and {len(rr.occurrences) - 5} more</li>"
                if len(rr.occurrences) > 5 else ""
            )
            result = f"<span class='fail'>{label}</span><ul class='occ'>{occs}{more}</ul>"
        out.append(
            f"<tr><td class='mono'>{rr.rule_id}</td>"
            f"<td>{html.escape(rr.name)}</td><td>{result}</td></tr>"
        )
    out.append("</table>")
    return "".join(out)
